export const navigationItems = [
  { label: 'Dashboard', path: '/', permission: 'dashboard.ver', icon: 'DB', available: true },
  {
    label: 'Productos', permission: 'productos.ver', icon: 'PR',
    children: [
      { label: 'Productos', path: '/products' },
      { label: 'Categorías', path: '/categories' },
      { label: 'Marcas', path: '/brands' },
      { label: 'Unidades', path: '/units' },
    ],
  },
  { label: 'Compras', path: '/purchases', permission: 'compras.ver', icon: 'CO', available: true },
  { label: 'Ventas', path: '/sales', permission: 'ventas.ver', icon: 'VE', available: true },
  { label: 'Caja', path: '/cash', permission: 'caja.movimientos', icon: 'CJ', available: true },
  { label: 'Inventario', path: '/inventory', permission: 'inventario.ver', icon: 'IN', available: true },
  { label: 'Clientes', path: '/clients', permission: 'clientes.ver', icon: 'CL', available: true },
  { label: 'Proveedores', path: '/suppliers', permission: 'proveedores.ver', icon: 'PV', available: true },
  { label: 'Usuarios', path: '/users', permission: 'usuarios.ver', icon: 'US', available: true },
  { label: 'Roles y permisos', path: '/roles', permission: 'roles.ver', icon: 'RP', available: true },
  { label: 'Bitácora', path: '/audit', permission: 'bitacora.ver', icon: 'BI', available: true },
  { label: 'Respaldos', path: '/backups', permission: 'respaldos.ver', icon: 'RS', available: true },
  { label: 'Reportes', path: '/reports', permission: 'reportes.ver', icon: 'RE', available: true },
  { label: 'Configuración', path: '/settings', permission: 'configuracion.ver', icon: 'CF', available: true },
  { label: 'Catálogo público', path: '/catalog', icon: 'CP', available: true, publicLink: true },
]
